/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
        // Apple-inspired brand colors
        brand: {
          50: '#e8f3ff',
          100: '#d3e8ff',
          200: '#b4d8ff',
          300: '#8ec4ff',
          400: '#5ba9ff',
          500: '#2997ff',
          600: '#0071e3',
          700: '#0066cc',
          800: '#005bb5',
          900: '#004a91',
          950: '#00366b',
          DEFAULT: '#0071e3',
          solid: '#0071e3',
          solid_hover: '#0066cc',
          tertiary: '#0066cc',
          primary_alt: '#2997ff',
          secondary: '#0066cc',
          secondary_hover: '#0071e3',
        },
        dark: {
          900: '#000000',
          800: '#1d1d1f',
        },
        overlay: 'rgba(0, 0, 0, 0.64)',
        disabled: '#d2d2d7',
        disabled_subtle: '#ededf2',
        active: '#ededf2',
        focus: {
          ring: '#0071e3',
        },
        fg: {
          primary: '#1d1d1f',
          secondary: 'rgba(0, 0, 0, 0.8)',
          tertiary: 'rgba(0, 0, 0, 0.64)',
          quaternary: 'rgba(0, 0, 0, 0.48)',
          quaternary_hover: '#1d1d1f',
          disabled: 'rgba(0, 0, 0, 0.35)',
          disabled_subtle: 'rgba(0, 0, 0, 0.3)',
          white: '#ffffff',
          brand: {
            primary: '#0071e3',
            primary_alt: '#2997ff',
            secondary: '#0066cc',
            secondary_alt: '#0066cc',
            secondary_hover: '#0071e3',
          },
          error: {
            primary: '#d92d20',
            secondary: '#f04438',
          },
          success: {
            secondary: '#039855',
          },
        },
        bg: {
          primary: '#ffffff',
          secondary: '#f5f5f7',
          tertiary: '#ededf2',
          active: '#ededf2',
          disabled_subtle: '#ededf2',
        },
        // Map functional colors
        success: {
          50: '#ecfdf3',
          100: '#d1fadf',
          500: '#039855',
          600: '#027a48',
          700: '#05603a',
          DEFAULT: '#039855',
        },
        warning: {
          50: '#fff8eb',
          100: '#feefc7',
          500: '#b54708',
          600: '#93370d',
          700: '#7a2e0e',
          DEFAULT: '#b54708',
        },
        error: {
          50: '#fef3f2',
          100: '#fde6e3',
          500: '#d92d20',
          600: '#b42318',
          700: '#912018',
          primary: '#d92d20',
          primary_hover: '#b42318',
          subtle: '#fda29b',
          solid: '#d92d20',
          solid_hover: '#b42318',
          DEFAULT: '#d92d20',
        },
        error_subtle: '#fda29b',
        brand_secondary: '#0066cc',
      },
      // Semantic text colors using CSS variables for dark mode support
      textColor: {
        primary: 'rgb(var(--color-text-primary) / <alpha-value>)',
        secondary: 'rgb(var(--color-text-secondary) / <alpha-value>)',
        tertiary: 'rgb(var(--color-text-tertiary) / <alpha-value>)',
        quaternary: 'rgb(var(--color-text-quaternary) / <alpha-value>)',
        placeholder: 'rgb(var(--color-text-tertiary) / <alpha-value>)',
        disabled: 'rgb(var(--color-text-tertiary) / 0.5)',
      },
      // Semantic background colors
      backgroundColor: {
        primary: 'rgb(var(--color-bg-primary) / <alpha-value>)',
        primary_hover: 'rgb(var(--color-bg-primary-hover) / <alpha-value>)',
        primary_alt: 'rgb(var(--color-bg-primary-alt) / <alpha-value>)',
        secondary: 'rgb(var(--color-bg-secondary) / <alpha-value>)',
        tertiary: 'rgb(var(--color-bg-tertiary) / <alpha-value>)',
        active: 'rgb(var(--color-bg-active) / <alpha-value>)',
        disabled_subtle: 'rgb(var(--color-bg-tertiary) / 0.5)',
      },
      // Semantic border colors
      borderColor: {
        primary: 'rgb(var(--color-border) / <alpha-value>)',
        secondary: 'rgb(var(--color-border) / <alpha-value>)',
      },
      // Ring colors
      ringColor: {
        primary: 'rgb(var(--color-border) / <alpha-value>)',
        secondary: 'rgb(var(--color-border) / <alpha-value>)',
        brand: 'rgb(22 163 74 / <alpha-value>)',
      },
      fontFamily: {
        sans: ['SF Pro Text', 'SF Pro Icons', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
        display: ['SF Pro Display', 'SF Pro Icons', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
      },
      fontSize: {
        md: ['1rem', { lineHeight: '1.47', letterSpacing: '-0.374px' }],
      },
      borderRadius: {
        'apple-sm': '5px',
        'apple': '8px',
        'apple-md': '11px',
        'apple-lg': '12px',
        'pill': '980px',
        'xl': '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
      },
      boxShadow: {
        xs: 'rgba(0, 0, 0, 0.08) 0 2px 6px 0',
        'xs-skeumorphic': 'rgba(0, 0, 0, 0.08) 0 2px 6px 0',
        card: 'rgba(0, 0, 0, 0.22) 3px 5px 30px 0px',
      },
    },
  },
  plugins: [],
}
